In [1]:
import pandas as pd
import numpy as np

In [2]:
mpg = pd.read_csv("../data/mpg.csv")
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [3]:
mpg.trans.unique()

array(['auto(l5)', 'manual(m5)', 'manual(m6)', 'auto(av)', 'auto(s6)',
       'auto(l4)', 'auto(l3)', 'auto(l6)', 'auto(s5)', 'auto(s4)'],
      dtype=object)

In [4]:
manual = mpg[mpg.trans.str.contains("manual")]
manual.to_csv("../data/manual.csv", index=False)

In [5]:
automatic = mpg[mpg.trans.str.contains("auto")]
automatic.to_csv("../data/automatic.csv", index=False)

In [6]:
mpg_all = pd.concat([manual, automatic])

In [7]:
melted_mpg = mpg[mpg.duplicated(subset=["manufacturer", "model", "year", "trans"]) == False].melt(id_vars = ["manufacturer", "model", "year", "trans"])
melted_mpg.to_csv("../data/melted_mpg.csv", index=False)

In [8]:
melted_mpg.pivot(index=["manufacturer", "model", "year", "trans"], columns="variable", values="value").reset_index()

variable,manufacturer,model,year,trans,class,cty,cyl,displ,drv,fl,hwy
0,audi,a4,1999,auto(l5),compact,18,4,1.8,f,p,29
1,audi,a4,1999,manual(m5),compact,21,4,1.8,f,p,29
2,audi,a4,2008,auto(av),compact,21,4,2.0,f,p,30
3,audi,a4,2008,manual(m6),compact,20,4,2.0,f,p,31
4,audi,a4 quattro,1999,auto(l5),compact,16,4,1.8,4,p,25
...,...,...,...,...,...,...,...,...,...,...,...
134,volkswagen,new beetle,2008,manual(m5),subcompact,20,5,2.5,f,r,28
135,volkswagen,passat,1999,auto(l5),midsize,18,4,1.8,f,p,29
136,volkswagen,passat,1999,manual(m5),midsize,21,4,1.8,f,p,29
137,volkswagen,passat,2008,auto(s6),midsize,19,4,2.0,f,p,28
138,volkswagen,passat,2008,manual(m6),midsize,21,4,2.0,f,p,29

In [9]:
mpg_class = mpg[["manufacturer", "model", "year", "class"]]
mpg_class = mpg_class[mpg_class.duplicated() == False]
mpg_class.to_csv("../data/mpg_class.csv", index=False)

In [10]:
mpg_data = mpg[["manufacturer", "model", "displ", "year", "cyl", "trans", "drv", "cty", "hwy", "fl"]]
mpg_data.to_csv("../data/mpg_no_class.csv", index=False)

In [11]:
pd.merge(mpg_data, mpg_class, how="left", on=["manufacturer", "model", "year"])

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [12]:
movies = pd.read_csv("../data/Pudding-Film-Dialogue.csv")
movies

,imdb_id,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,runtimeMinutes,genres
0,tt0112579,The Bridges of Madison County,1995,Betty,woman,311,0.048639,35.0,142.0,135,Drama
1,tt0112579,The Bridges of Madison County,1995,Carolyn Johnson,woman,873,0.136534,NaN,142.0,135,Drama
2,tt0112579,The Bridges of Madison County,1995,Eleanor,woman,138,0.021583,NaN,142.0,135,Drama
3,tt0112579,The Bridges of Madison County,1995,Francesca Johns,woman,2251,0.352049,46.0,142.0,135,Drama
4,tt0112579,The Bridges of Madison County,1995,Madge,woman,190,0.029715,46.0,142.0,135,Drama
...,...,...,...,...,...,...,...,...,...,...,...
23042,tt0101414,Beauty and the Beast,1991,Lumiere,man,1063,0.104636,56.0,452.0,84,Animation
23043,tt0101414,Beauty and the Beast,1991,Maurice,man,1107,0.108967,71.0,452.0,84,Animation
23044,tt0101414,Beauty and the Beast,1991,Monsieur D'Arqu,man,114,0.011222,58.0,452.0,84,Animation
23045,tt0101414,Beauty and the Beast,1991,Mrs. Potts,woman,564,0.055517,66.0,452.0,84,Animation
23046,tt0101414,Beauty and the Beast,1991,Wardrobe,woman,121,0.011911,54.0,452.0,84,Animation

In [22]:
movies[movies.title.str.contains("M[ae]n")].groupby("title").count()

,imdb_id,release_year,character,gender,words,proportion_of_dialogue,age,gross,runtimeMinutes,genres
title,,,,,,,,,,
3 Men and a Baby,11,11,11,11,11,11,6,11,11,11
A Few Good Men,20,20,20,20,20,20,18,20,20,20
A Man Apart,12,12,12,12,12,12,7,12,12,12
A Most Wanted Man,14,14,14,14,14,14,14,14,14,14
A Serious Man,14,14,14,14,14,14,4,14,14,14
A Single Man,7,7,7,7,7,7,6,7,7,7
All the Boys Love Mandy Lane,7,7,7,7,7,7,5,0,7,7
All the President's Men,12,12,12,12,12,12,11,0,12,12
Austin Powers: International Man of Mystery,10,10,10,10,10,10,10,10,10,10
Bloodfist VII: Manhunt,9,9,9,9,9,9,6,0,9,9
Brick Mansions,11,11,11,11,11,11,6,11,11,11
Cecil B. DeMented,21,21,21,21,21,21,11,21,21,21
Children of Men,10,10,10,10,10,10,10,10,10,10
Delivery Man,11,11,11,11,11,11,3,11,11,11
Demolition Man,9,9,9,9,9,9,7,9,9,9
Friday the 13th Part VIII: Jason Takes Manhattan,13,13,13,13,13,13,9,13,13,13
Hollow Man,8,8,8,8,8,8,8,8,8,8
Inside Man,16,16,16,16,16,16,13,16,16,16
Last Man Standing,11,11,11,11,11,11,9,11,11,11
Little Man Tate,9,9,9,9,9,9,8,9,9,9
Man Trouble,14,14,14,14,14,14,13,14,14,14
Man Up,8,8,8,8,8,8,8,0,8,8
Man on Fire,9,9,9,9,9,9,7,9,9,9
Man on the Moon,19,19,19,19,19,19,13,19,19,19
Mandingo,8,8,8,8,8,8,7,0,8,8
Manhattan Murder Mystery,10,10,10,10,10,10,9,10,10,10
Manhunter,14,14,14,14,14,14,11,14,14,14
Matchstick Men,8,8,8,8,8,8,6,8,8,8
Memoirs of an Invisible Man,13,13,13,13,13,13,12,13,13,13
Men in Black,10,10,10,10,10,10,9,10,10,10
Men in Black 3,15,15,15,15,15,15,6,15,15,15
Mystery Men,14,14,14,14,14,14,14,14,14,14
No Country for Old Men,14,14,14,14,14,14,10,14,14,14
Nothing But a Man,10,10,10,10,10,10,7,0,10,10
Pirates of the Caribbean: Dead Man's Chest,12,12,12,12,12,12,12,12,12,12
Repo Man,15,15,15,15,15,15,12,0,15,15
Spider-Man 2,9,9,9,9,9,9,8,9,9,9
Star Wars: Episode I - The Phantom Menace,19,19,19,19,19,19,17,19,19,19
The Company Men,14,14,14,14,14,14,11,14,14,14
The Elephant Man,11,11,11,11,11,11,10,0,11,11
The Family Man,20,20,20,20,20,20,17,20,20,20
The Leopard Man,12,12,12,12,12,12,10,0,12,12
The Man Who Knew Too Much,17,17,17,17,17,17,16,0,17,17
The Man in the Iron Mask,11,11,11,11,11,11,7,11,11,11
The Manchurian Candidate,13,13,13,13,13,13,12,13,13,13
The Marrying Man,10,10,10,10,10,10,9,10,10,10
The Men Who Stare at Goats,8,8,8,8,8,8,8,8,8,8
The November Man,10,10,10,10,10,10,8,10,10,10
The Omega Man,6,6,6,6,6,6,6,0,6,6
The Stunt Man,14,14,14,14,14,14,10,0,14,14
The Thin Man,11,11,11,11,11,11,11,0,11,11
The Third Man,11,11,11,11,11,11,11,11,11,11
The Weather Man,8,8,8,8,8,8,5,8,8,8
Tin Men,13,13,13,13,13,13,13,13,13,13
X-Men,8,8,8,8,8,8,6,8,8,8
X-Men 2,12,12,12,12,12,12,12,12,12,12
X-Men Origins: Wolverine,14,14,14,14,14,14,9,14,14,14
Yes Man,22,22,22,22,22,22,8,22,22,22

In [26]:
pd.to_datetime(movies.release_year, format="%Y")

0       1995-01-01
1       1995-01-01
2       1995-01-01
3       1995-01-01
4       1995-01-01
           ...
23042   1991-01-01
23043   1991-01-01
23044   1991-01-01
23045   1991-01-01
23046   1991-01-01
Name: release_year, Length: 23047, dtype: datetime64[ns]